services:
  verdaccio:
    build:
      context: ./verdaccio
      dockerfile: .dockerfile
    profiles: ["verdaccio"]
    environment:
      - PLUGIN_AUTH_GITLAB_APPLICATION_ID=${PLUGIN_AUTH_GITLAB_APPLICATION_ID}
      - PLUGIN_AUTH_GITLAB_APPLICATION_SECRET=${PLUGIN_AUTH_GITLAB_APPLICATION_SECRET}
    container_name: verdaccio
    restart: unless-stopped
    ports:
      - "4873:4873"
    volumes:
      - verdaccio-storage:/verdaccio/storage
      - verdaccio-conf:/verdaccio/conf
    networks:
      - npm-network
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      # Création automatique de la base et de l'utilisateur
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - gitlab-network
    env_file:
      - .env 

  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: unless-stopped
    hostname: gitlab.local
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    depends_on:
      - postgres
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.local'
        ## Désactive le PostgreSQL intégré
        postgresql['enable'] = false
        ## Pointage vers la base externe
        gitlab_rails['db_adapter']   = 'postgresql'
        gitlab_rails['db_encoding']  = 'unicode'
        gitlab_rails['db_host']      = 'postgres'
        gitlab_rails['db_port']      = 5432
        gitlab_rails['db_username']  = '${POSTGRES_USER}'
        gitlab_rails['db_password']  = '${POSTGRES_PASSWORD}'
        gitlab_rails['db_database']  = '${POSTGRES_DB}'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    networks:
      - gitlab-network
      - npm-network
    env_file:
      - .env 

volumes:
  postgres-data:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  verdaccio-storage:
  verdaccio-conf:

networks:
  gitlab-network:
  npm-network:
